### ISSUE TITLE
SUID Sandbox not configured correctly

### ISSUE THREAD

**Issue by gusmacaulay** [latter-bolden/port#10]
$taisho
[20213:0414/170058.299970:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /usr/lib/taisho/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap

**Comment by gusmacaulay** [comment]
On Debian 10 still

**Comment by gusmacaulay** [comment]
can use the --no-sandbox option as a workaround same as this https://github.com/jely2002/youtube-dl-gui/issues/26

**Comment by arthyn** [comment]
Seems like this has been a persistent issue with Electron. They supposedly added something to fix it in the debian packager, but I'll try digging into why it's not working.

**Comment by arthyn** [comment]
Figured it out, but doesn't require any code changes. I just need to build the binary on Linux. Will include with the next release.

**Comment by h5gq3** [comment]
I still had this now and I had to manually set owner of chrome-sandbox to root and mode to 4755
