### ISSUE TITLE
cannot upload avatar image

### ISSUE THREAD

**Issue by spalfs** [latter-bolden/port#100]
i click on blue upload text and nothing happens
![image-title](https://i.imgur.com/ivFdpMB.png)

**Comment by arthyn** [comment]
This is likely an issue with Landscape. Do you have an S3 compatible provider hooked up in your system settings?

**Comment by spalfs** [comment]
nope

**Comment by arthyn** [comment]
Gotcha so yeah you have to hook one up to be able to upload images. Going to go ahead and close this. 
~sitful-hatred on the network writes really good guides, here's one about configuring S3 https://subject.network/posts/configuring-s3-urbit/
