### ISSUE TITLE
Hangs forever when booting planet

### ISSUE THREAD

**Issue by adamenglebright** [latter-bolden/port#102]
<img width="1277" alt="Screenshot 2021-06-01 at 10 01 12" src="https://user-images.githubusercontent.com/8036282/120297434-00a19c00-c2c1-11eb-8e9f-8fa5362068bb.png">
When I try to boot my planet, it hangs on the "booting planet" screen for hours and doesn't do anything. When I try to 'eject' it also hangs forever.

**Comment by arthyn** [comment]
@adamenglebright if you still have it open, can you click the little bug in the right hand corner? You should see dev tools pop up in the main window, and also a background window with dev tools. In the bg dev tools, click console and scroll to see if there's any errors. 

If you don't see any, is it possible you are on an M1 mac? Urbit currently doesn't support M1 macs and Port doesn't warn or fail well yet. It's on my to do list though.

**Comment by arthyn** [comment]
Closing this until I hear more feedback

**Comment by adamenglebright** [comment]
Hi—apologies, Github didn't notify me about this! I am indeed on an M1 Mac, that answers that! Thank you :)
