### ISSUE TITLE
Port stuck loading when trying to eject ship

### ISSUE THREAD

**Issue by sambex-fadsen** [latter-bolden/port#104]

**Comment by arthyn** [comment]
@sambex-fadsen if you still have it open, can you click the little bug in the right hand corner? You should see dev tools pop up in the main window, and also a background window with dev tools. In the background dev tools, click console and scroll to see if there's any errors.

Also, can you give more details about the ship in question and your environment (MacOS version/Linux Distro). Did you boot it through Port or was it imported?

**Comment by arthyn** [comment]
Closing this until I hear more feedback
