### ISSUE TITLE
Can't get past authorisation screen

### ISSUE THREAD

**Issue by gusmacaulay** [latter-bolden/port#11]

**Comment by gusmacaulay** [comment]
Can't seem to click on the 'copy code' button

**Comment by arthyn** [comment]
When you try to click copy code do you see it say 'copied!' or it just doesn't do anything? Either way, is there an error in dev tools?

**Comment by gusmacaulay** [comment]
no, there is no response.  I think there is a more general problem of something weird happening with clicking on things, on all the buttons I have to click under them to get a response - maybe the problem with the copy code button is there is no space around it I can click to get it to work.

**Comment by gusmacaulay** [comment]
have been able to test this again, the issue still occurs, but by resizing the window it goes away.  Suspect some gnome-shell electron weirdness at play.

**Comment by arthyn** [comment]
@gusmacaulay I'm curious if this was fixed by any of the new versions?

**Comment by gusmacaulay** [comment]
I tried installing the latest and the issue is still there, although mentioned above the workaround is fairly trivial now.   I'm not sure whats going on with the debian package as installed the latest but when I check the version from the menu it still says 0.41.

**Comment by arthyn** [comment]
That's really strange it should be 1.0 or 1.1. 

I'm going to go ahead and close this unless you'd like to screen share or something. I don't really have a way to debug and haven't heard any other reports of similar issues.
