### ISSUE TITLE
Reset of Group Sort Order

### ISSUE THREAD

**Issue by rabfel-hobmet** [latter-bolden/port#112]
**Bug Description*
After each port restart, my group sort order is reset to "last updated". 

**To Reproduce**
1. Navigate to group
2. Change sort order to "A-Z"
3. Close Port
4. Reopen Port
5. Navigate to same group
6. Sort order is reset to "Last Updated"

**Expected Behavior**
Settings should retain between restarts. 

**Screenshots**
![image](https://user-images.githubusercontent.com/76716724/122156055-0fd62d00-ce1d-11eb-806f-b4170bea64ec.png)

![image](https://user-images.githubusercontent.com/76716724/122156068-182e6800-ce1d-11eb-8076-6120cd45aaa8.png)

**Environment:**
 - OS: [Ubuntu]
 - Version: [20.04.2 LTS]
 - Port Version: [1.1.0]

**Additional context**
Seems cookie related.

**Comment by arthyn** [comment]
Thanks for reporting this, I think we can handle sessions a little better to prevent this in the future. I'll get it on the roadmap.

**Comment by arthyn** [comment]
Should be fixed in latest update
