### ISSUE TITLE
Need a way to drop down to dojo when landscape fails

### ISSUE THREAD

**Issue by baudtack** [latter-bolden/port#113]
When landscape bugs prevent it loading properly, port really could use a way to pull up the dojo to debug the problem. Currently you have to shut the ship down and run it manually.

**Comment by arthyn** [comment]
Yeah I definitely agree. I think there's two stories here. The quick one which I think is just spawn a terminal with the boot command and another where once haskell king is in place we offer a way for you to connect remotely. 

I'll likely do the first option in the next release. Thanks!
