### ISSUE TITLE
Updated app icon to match the theme of macOS Big Sur

### ISSUE THREAD

**Issue by dietofworms** [latter-bolden/port#114]
I have gone ahead and created a simple app icon which matches the design of macOS Big Sur. Happy to share the .psd file if required but here's what it looks like in the dock:
<img width="65" alt="Screen Shot 2021-06-24 at 2 17 55 pm" src="https://user-images.githubusercontent.com/28944297/123205820-e775bf00-d4fd-11eb-9757-af3dddc2e4a2.png">

and the image itself (png)
![Urbit-Port](https://user-images.githubusercontent.com/28944297/123205692-b39a9980-d4fd-11eb-84b7-f740e7f5569d.png)

**Comment by arthyn** [comment]
Awesome thanks for this! I'll get it in the next release.

**Comment by dietofworms** [comment]
@arthyn want me to share with you the photoshop file?
