### ISSUE TITLE
No Sound - Links in Chat

### ISSUE THREAD

**Issue by rabfel-hobmet** [latter-bolden/port#115]
**Bug Description*
Unable to get sound to work when linking video from digital ocean space to urbit on Port.

**To Reproduce**
1. Post video into chat on Port uploading to space on Digital Ocean
2. Click either drop down video link or "new window" hyperlink
3. No Sound
4. Volume at max, but tried changing.
5. Checked settings

**Expected Behavior**
Currently working with sound on mobile/desktop web browsers.

**Environment:**
 - Ubuntu
 -  20.04.2 LTS
 - Port Version: 1.1.0

**Comment by arthyn** [comment]
Good catch, is this on the snap install?

**Comment by arthyn** [comment]
Closing until I hear back
