### ISSUE TITLE
[bug] unable to join group, exception thrown “Cannot read property 'metadata' of undefined”

### ISSUE THREAD

**Issue by jl111** [latter-bolden/port#121]
**Bug Description*
Unable to join a group. 
See video below for how to reproduce issue. 

see screenshot
**To Reproduce**
see video below: open port and try to join a new group

**Expected Behavior**
able to join group or get a message letting me know that a group does not exist, do not throw an exception. 
**Screenshots**

https://user-images.githubusercontent.com/15962156/132263994-2b99f6f8-241b-4451-8270-0b4ecaf591fd.mov

**Environment:**
macbook pro specs: 
![image](https://user-images.githubusercontent.com/15962156/132264080-685a8a25-66d9-4507-919a-77c0e30476f8.png)

 - OS: [e.g. MacOS]
 - Version: [e.g. 22]
 - Port Version: [e.g. 1.0.1]

**Additional context**

If you still have it open, click the little bug in the right hand corner. You should see dev tools pop up in the main window, and also a background window with dev tools. Check either of the dev tools, click console and scroll to see if there's any errors, include those if possible.

- didn't see any errors in the console

**Comment by arthyn** [comment]
Hey @jl111 thanks for reporting this. This is actually an issue with Landscape itself and not Port. You can see here urbit/landscape#1137 which we should have a fix for soon, just needs to be released.
