### ISSUE TITLE
0.4.0 - disconnecting remote ship says you're deleting it

### ISSUE THREAD

**Issue by tinnus-napbus** [latter-bolden/port#14]
if you disconnect a remote ship it has the same button and gives the same warning as if you were physically deleting a local ship which is confusing

![2021-04-18_02h45m51s](https://user-images.githubusercontent.com/77721746/115117517-10a43b80-9ff3-11eb-84ef-93ff334c43b7.png)

**Comment by Vrend** [comment]
+1, also thought this was confusing
