### ISSUE TITLE
0.4.0 - Cannot stop any pier

### ISSUE THREAD

**Issue by Vrend** [latter-bolden/port#19]
Running on Manjaro Linux XFCE

Attempting to press the stop button does nothing. Have tested in two instances, with both a moon and a comet, all attempts fail. Below is attempt 2 with a moon:
![image](https://user-images.githubusercontent.com/8152392/115124001-e2d8db80-9f8d-11eb-8fe3-9c7bb3986068.png)

**Comment by arthyn** [comment]
If you click stop and open dev tools, you should see a background window. Are there any errors there when you try to stop?

**Comment by Vrend** [comment]
This is the output when pressing stop: 
![image](https://user-images.githubusercontent.com/8152392/115160505-7da4e900-a066-11eb-88a9-d17dba2b6819.png)
