### ISSUE TITLE
.deb package install won't run (missing libX11-xcb.so.1)

### ISSUE THREAD

**Issue by gusmacaulay** [latter-bolden/port#2]
Tried out the .deb package, on debian 10, using open with software installer.  Install completes but it won't run.

```
$ taisho 
taisho: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory
```

**Comment by arthyn** [comment]
Hey @gusmacaulay sorry this took so long, but can you try this release to see if it works? https://hmillerdev.nyc3.digitaloceanspaces.com/taisho_0.3.1_amd64.deb

**Comment by gusmacaulay** [comment]
Latest release fixed this problem.
