### ISSUE TITLE
0.4.1 - developer tools stop things from loading

### ISSUE THREAD

**Issue by tinnus-napbus** [latter-bolden/port#24]
after opening and closing dev tools, things don't load any more:

![2021-04-19_19h04m08s](https://user-images.githubusercontent.com/77721746/115195684-26c11180-a143-11eb-821a-4e56eef69dd1.png)

and when I close taisho I get:

![2021-04-19_19h04m16s](https://user-images.githubusercontent.com/77721746/115195711-32143d00-a143-11eb-980d-d22aef4d0179.png)

**Comment by arthyn** [comment]
This is because one of those windows is actually the service running everything. I need to make sure it gets hidden instead of closed when you click the X. Thanks!
