### ISSUE TITLE
Assertion '0' failed in vere/foil.c:56

### ISSUE THREAD

**Issue by ohAitch** [latter-bolden/port#6]
![_Applications_taisho app_Contents_Resources_app_ webpack_renderer_main_window_index html](https://user-images.githubusercontent.com/1857414/114072945-fd110c00-985f-11eb-883e-15d21b9f58dd.png)

(As a minor request on top of the "comet doesn't boot", detecting the `bail` and cancelling the "booting" spinner in favor of the full log would be neat.)

**Comment by arthyn** [comment]
Thanks, did you happen to catch the error right above that line? Or was it not visible? If not, do you mind booting another comet and clicking the little bug in the right hand corner. It should show you any errors that come up.

But yeah you're right I need to handle boot failures better, thanks!

**Comment by ohAitch** [comment]
Oh yep I see boot messages (json cleaned up):

```
10:35:27 ~
urbit 1.3
boot: home is ///Users/fyr/Library/Application Support/taisho/piers/pittyp-mbp
loom: mapped 2048MB
lite: arvo formula 79925cca
lite: core 59f6958
lite: final state 59f6958
boot: downloading pill https://bootstrap.urbit.org/urbit-v1.3.pill
10:35:29 boot: mining a comet. May take up to an hour.
If you want to boot faster, get an Urbit identity.
10:36:15 boot: found comet ~lagbyn-tobfun-simder-podned--rivdux-dovwes-saptel-wanzod
10:36:15 boot: retrieving latest block
10:36:16 boot: verifying keys
10:36:16 boot: getting sponsor
10:36:16 boot: retrieving galaxy table
10:36:32 boot: retrieving network domains
10:36:32 boot: retrieving keys for sponsor ~wanzod
10:36:33 boot: retrieving keys for sponsor ~zod
10:36:33 /Users/fyr/Library/Application Support/taisho/piers/pittyp-mbp: error: no such file or directory
10:36:33 
Assertion '0' failed in vere/foil.c:56

bail: oops
bailing out
```

Did it fail to create the pier?

And yeah the error got truncated off on the right
![_Applications_taisho app_Contents_Resources_app_ webpack_renderer_main_window_index_root html](https://user-images.githubusercontent.com/1857414/114087212-d6a79c80-9870-11eb-8c58-524657e0a2a8.png)

**Comment by arthyn** [comment]
Looks like it did. Did you see any other errors in the console? Perhaps the folder wasn't able to be made for some reason. You can see if you're able to jump into the terminal by entering: 

```
cd /Users/fyr/Library/Application\ Support/taisho/piers
ls
```

This should show `pittyp-mbp` if it was successful at making the folder.

**Comment by arthyn** [comment]
Actually I think I know what's wrong. I made that piers directory manually on my machine 🤦🏼‍♂️, but the app isn't ensuring it exists/gets created.

**Comment by ohAitch** [comment]
Hah yep sounds right
```
➤ cd ~/Library/Application\ Support/taisho/piers
cd: The directory '/Users/fyr/Library/Application Support/taisho/piers' does not exist
```
