### ISSUE TITLE
0.6.0 - small window needs better responsiveness

### ISSUE THREAD

**Issue by arthyn** [latter-bolden/port#86]
For example details screens lose back button, bad logo scaling on home screen, etc.

reported by ~monted-tallex

**Comment by vincepmartin** [comment]
I'd like to tackle this.  Lately I have been working with react + tailwind quite a bit on other projects.

**Comment by arthyn** [comment]
Sure thing! Let me know if you have questions or need help. I'm usually on the network ~nocsyx-lassul
